// Social Links and Contact Information
var youtube = "#";
var twitter = "#";
var password = "falcon98";
var linkedin = "https://www.linkedin.com/in/ashen-wijesingha/";
var instagram = "https://www.instagram.com/ashen_wijesingha/";
var github = "https://github.com/Falcon-98";
var email = 'mailto:terminal@falcon98.com';
var website = "https://falcon98.com/";

// Personal Links
var pfacebook = "https://www.facebook.com/ashen.dilshan.96/";
var plinkedin = "https://www.linkedin.com/in/ashen-wijesingha/";
var pinstagram = "https://www.instagram.com/ashen_wijesingha/";
var pgithub = "https://github.com/AshenWijesingha";
var pemail = 'mailto:a.d.wijesingha@gmail.com';
var pcontact = 'tel:+94784464128';
var pwebsite = 'https://ashenwijesingha.github.io';
var pmedium = 'https://medium.com/@a.d.wijesingha';

// Project Links
var qr = "https://ashenwijesingha.github.io/QR-Code-Generator/";

// Banner ASCII Art
banner = [
  "",
  "  ███████╗ █████╗ ██╗      ██████╗ ██████╗ ███╗   ██╗ █████╗  █████╗ ",
  "  ██╔════╝██╔══██╗██║     ██╔════╝██╔═══██╗████╗  ██║██╔══██╗██╔══██╗",
  "  █████╗  ███████║██║     ██║     ██║   ██║██╔██╗ ██║╚██████║╚█████╔╝",
  "  ██╔══╝  ██╔══██║██║     ██║     ██║   ██║██║╚██╗██║ ╚═══██║██╔══██╗",
  "  ██║     ██║  ██║███████╗╚██████╗╚██████╔╝██║ ╚████║ █████╔╝╚█████╔╝",
  "  ╚═╝     ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝ ╚════╝  ╚════╝ ",
  "",
  "  ╔══════════════════════════════════════════════════════════════════╗",
  "  ║                     🚀 FALCON 98 TERMINAL                       ║",
  "  ║              Pioneering Technology Services Provider             ║",
  "  ╚══════════════════════════════════════════════════════════════════╝",
  "",
  "  🌟 Welcome to Ashen Wijesingha's professional terminal!",
  "  💻 Type 'help' to see available commands",
  "  🔍 Use TAB for command completion",
  "  📚 Try 'neofetch' for system information",
  "",
];

// Company Information
whois = [
  "",
  "╭─────────────────────────────────────────────────────────────────╮",
  "│                        🏢 ABOUT FALCON 98                      │",
  "├─────────────────────────────────────────────────────────────────┤",
  "│                                                                 │",
  "│  Falcon 98 is a pioneering technology services provider,        │",
  "│  founded by Ashen Wijesingha, dedicated to guiding businesses   │",
  "│  through the digital era with innovative solutions.             │",
  "│                                                                 │",
  "│  🎯 Our Mission: Innovation + Excellence + Customer Success     │",
  "│  🔧 Services: Custom Software, Web Development, Consulting      │",
  "│  🌍 Vision: Empowering organizations for digital success        │",
  "│                                                                 │",
  "│  We seamlessly integrate cutting-edge technology with industry  │",
  "│  expertise to deliver tailored solutions that drive growth.     │",
  "│  Specializing in cybersecurity, cloud solutions, and DevSecOps. │",
  "│                                                                 │",
  "╰─────────────────────────────────────────────────────────────────╯",
  "",
];

// Personal Information
whoami = [
  "",
  "╭─────────────────────────────────────────╮",
  "│  🤔 The eternal question: 'Who am I?'  │",
  "├─────────────────────────────────────────┤",
  "│                                         │",
  "│  The paradox is: we never truly know,  │",
  "│  but we constantly discover ourselves   │",
  "│  through our experiences and choices.   │",
  "│                                         │",
  "│  Right now, you're exploring the       │",
  "│  digital footprint of a cybersecurity  │",
  "│  professional and innovator... 🚀       │",
  "│                                         │",
  "╰─────────────────────────────────────────╯",
  "",
];

// About Information
about = [
  "",
  "╭────────────────────────────────────────────────────────────────╮",
  "│                      👨‍💻 ASHEN WIJESINGHA                        │",
  "├────────────────────────────────────────────────────────────────┤",
  "│                                                                │",
  "│  🏢 Current: Cyber Security Analyst @ EGUARDIAN               │",
  "│  🎓 Education: SLIIT (BSc Software Engineering)               │",
  "│  🏛️  Advanced Studies: Harvard University                      │",
  "│  📍 Location: Colombo, Sri Lanka 🇱🇰                          │",
  "│  🎂 Born: July 30, 1998 (Age 25)                             │",
  "│                                                                │",
  "│  🚀 Founder & CEO of Falcon 98 Corporation                    │",
  "│  🔐 Specializing in Cybersecurity & Cloud Solutions           │",
  "│  🌐 UI/UX Designer & Full-Stack Web Developer                 │",
  "│                                                                │",
  "│  Passionate about creating innovative digital solutions that   │",
  "│  bridge the gap between security and user experience. Always  │",
  "│  learning, always building, always securing.                  │",
  "│                                                                │",
  "╰────────────────────────────────────────────────────────────────╯",
  "",
];

// Skills Information
skills = [
  "",
  "╭─────────────────────────────────────────────────────────────────╮",
  "│                      🛠️  TECHNICAL EXPERTISE                    │",
  "├─────────────────────────────────────────────────────────────────┤",
  "│                                                                 │",
  "│  💻 Programming Languages:                                      │",
  "│     • C/C++ (Expert)         • JavaScript (Intermediate)      │",
  "│     • Python (Intermediate)  • PHP (Intermediate)             │",
  "│     • HTML/CSS (Expert)      • .NET (Intermediate)            │",
  "│                                                                 │",
  "│  🌐 Web & Frontend Technologies:                               │",
  "│     • React (Beginner)       • Angular (Intermediate)         │",
  "│     • WordPress/CMS (Expert) • UI/UX Design                   │",
  "│                                                                 │",
  "│  🔐 Cybersecurity & DevSecOps:                                 │",
  "│     • Cloud & Endpoint Security  • Security Operations        │",
  "│     • DevSecOps Pipeline         • Security Automation        │",
  "│     • Platform Engineering       • ML-Ops Security           │",
  "│                                                                 │",
  "│  ☁️  Cloud & Infrastructure:                                   │",
  "│     • AWS Clouds             • Kubernetes (K8S)              │",
  "│     • Docker                 • Rancher                       │",
  "│     • Jenkins                • Helm Charts                   │",
  "│                                                                 │",
  "│  🎨 Design & Tools:                                            │",
  "│     • Adobe Photoshop (Intermediate)                          │",
  "│     • Site Reliability Engineering                            │",
  "│                                                                 │",
  "╰─────────────────────────────────────────────────────────────────╯",
  "",
];

// Experience Information
experience = [
  "",
  "╭────────────────────────────────────────────────────────────────╮",
  "│                    💼 PROFESSIONAL EXPERIENCE                  │",
  "├────────────────────────────────────────────────────────────────┤",
  "│                                                                │",
  "│  🔐 EGUARDIAN                                                 │",
  "│     Cyber Security Analyst                     2023 - Present │",
  "│     • Cloud & Endpoint Security specialist                    │",
  "│     • DevSecOps and Platform Engineering                      │",
  "│     • ML-Ops security implementation                          │",
  "│     • Security automation and operations                      │",
  "│     • Fostering robust security practices                     │",
  "│                                                                │",
  "│  📚 Wiley Corporation                                         │",
  "│     Site Reliability Engineer Intern           2022 - 2023    │",
  "│     • Worked with K8S, Docker, Rancher, Helm                 │",
  "│     • Jenkins CI/CD pipeline management                       │",
  "│     • AWS cloud infrastructure management                     │",
  "│     • Infrastructure automation and monitoring                │",
  "│                                                                │",
  "│  🚀 Falcon 98 Corporation                                    │",
  "│     Founder & CEO                               2020 - Present │",
  "│     • Founded technology services company                     │",
  "│     • Led development of 50+ web applications                 │",
  "│     • Specialized in cybersecurity solutions                  │",
  "│     • Consulting for tech startups and businesses            │",
  "│                                                                │",
  "│  💡 Freelance Developer                                       │",
  "│     Full-Stack Developer & UI/UX Designer      2018 - 2020    │",
  "│     • Delivered custom solutions for 30+ clients             │",
  "│     • E-commerce and business automation specialist           │",
  "│     • 24/7 availability for professional opportunities        │",
  "│                                                                │",
  "╰────────────────────────────────────────────────────────────────╯",
  "",
];

// Education Information
education = [
  "",
  "╭─────────────────────────────────────────────────────────────────╮",
  "│                          🎓 EDUCATION                           │",
  "├─────────────────────────────────────────────────────────────────┤",
  "│                                                                 │",
  "│  🏛️  Harvard University                                         │",
  "│     Advanced Studies in Artificial Intelligence  2023 - Present │",
  "│     • Specialization in AI and Machine Learning                │",
  "│     • Research in AI-driven security solutions                 │",
  "│     • ML-Ops and AI automation techniques                      │",
  "│                                                                 │",
  "│  🏫 Sri Lanka Institute of Information Technology (SLIIT)      │",
  "│     BSc (Hons) Software Engineering            2019 - 2022     │",
  "│     • Specializing in Cyber Security                           │",
  "│     • Graduated December 15-16, 2022 at Malabe Campus         │",
  "│     • Focus on Software Engineering and Security               │",
  "│     • Thesis: Cybersecurity in Modern Applications            │",
  "│                                                                 │",
  "│  🎖️  Leadership & Certifications:                              │",
  "│     • IEEE Computer Society Chairperson (2023/24)             │",
  "│     • Vice President - Software Engineering Community          │",
  "│     • Technical Assistant - IEEE Students Branch SLIIT        │",
  "│     • Key contributor to SLIIT Xtreme 2.0 success             │",
  "│                                                                 │",
  "│  📚 Continuous Learning:                                       │",
  "│     • DevSecOps and Cloud Security Certifications             │",
  "│     • Site Reliability Engineering                             │",
  "│     • Multiple cybersecurity and cloud certifications         │",
  "│                                                                 │",
  "╰─────────────────────────────────────────────────────────────────╯",
  "",
];

// Leadership Information
leadership = [
  "",
  "╭─────────────────────────────────────────────────────────────────╮",
  "│                    🏆 LEADERSHIP & ACHIEVEMENTS                 │",
  "├─────────────────────────────────────────────────────────────────┤",
  "│                                                                 │",
  "│  🎯 IEEE Computer Society @ SLIIT                              │",
  "│     Chairperson                                 2023 - 2024     │",
  "│     • Led deployment of IEEE Computer Society website          │",
  "│     • Managed development of multiple chapter websites         │",
  "│     • Coordinated technical events and workshops               │",
  "│                                                                 │",
  "│  👥 Software Engineering Student Community                     │",
  "│     Vice President                              2021 - 2022     │",
  "│     • Key contributor to SLIIT Xtreme 2.0 success            │",
  "│     • Organized coding competitions and hackathons             │",
  "│     • Mentored junior students in programming                  │",
  "│                                                                 │",
  "│  🔧 IEEE Students Branch SLIIT                                │",
  "│     Technical Assistant                         2020 - 2023     │",
  "│     • Volunteered for multiple technical events                │",
  "│     • Provided technical support for conferences               │",
  "│     • Assisted in workshop organization and execution          │",
  "│                                                                 │",
  "│  🌟 Recognition & Testimonials:                                │",
  "│     • 'One of the most humble, intelligent, and helpful        │",
  "│       individuals at SLIIT' - Peer Reviews                     │",
  "│     • Praised for dedication, leadership, and problem-solving  │",
  "│     • Senior student recognition for outstanding contributions  │",
  "│                                                                 │",
  "╰─────────────────────────────────────────────────────────────────╯",
  "",
];

// Projects Information
projects = [
  "",
  "╭───────────────────────────────────────────────────────────────────╮",
  "│                        🔧 FEATURED PROJECTS                      │",
  "├───────────────────────────────────────────────────────────────────┤",
  "│                                                                   │",
  "│  🔐 Cybersecurity Solutions @ EGUARDIAN                         │",
  "│     Enterprise-grade security implementations                    │",
  "│     • Cloud & endpoint security automation                       │",
  "│     • DevSecOps pipeline integration                            │",
  "│     • ML-powered threat detection systems                       │",
  "│                                                                   │",
  "│  🌐 IEEE Computer Society Website                               │",
  "│     Full-stack web development and deployment                    │",
  "│     • Led the design and development as Chairperson            │",
  "│     • Managed multiple chapter website developments             │",
  "│     • Implemented modern web technologies and best practices    │",
  "│                                                                   │",
  "│  🎯 QR Code Generator                                           │",
  '│     Advanced QR code creation tool with modern UI               │',
  '│     → <a href="' + qr + '" target="_blank">Try it out</a>                                       │',
  "│     • Built with modern web technologies                        │",
  "│     • Features dynamic QR code generation and customization     │",
  "│                                                                   │",
  "│  💼 E-Commerce & Business Automation                            │",
  "│     Custom solutions for multiple clients                       │",
  "│     • 50+ web applications developed through Falcon 98         │",
  "│     • Payment integration and security implementations          │",
  "│     • Business process automation solutions                     │",
  "│     • Improved client efficiency by 70%+                       │",
  "│                                                                   │",
  "│  🚀 Infrastructure & DevOps Projects                           │",
  "│     Site reliability and infrastructure automation              │",
  "│     • Kubernetes and Docker containerization                    │",
  "│     • Jenkins CI/CD pipeline implementations                    │",
  "│     • AWS cloud infrastructure management                       │",
  "│                                                                   │",
  "│  🌐 Personal Portfolio & Terminal                              │",
  "│     Interactive web-based portfolio and terminal                │",
  "│     → You're using it right now! 😊                            │",
  "│     • Modern terminal interface with 25+ commands              │",
  "│     • Professional portfolio showcase                           │",
  "│                                                                   │",
  "╰───────────────────────────────────────────────────────────────────╯",
  "",
  "💡 Many projects are enterprise/confidential. Contact me to discuss specific implementations!",
  "",
];

// Social Links
social = [
  "",
  "╭─────────────────────────────────────────────────────╮",
  "│                🌐 SOCIAL & PROFESSIONAL            │",
  "├─────────────────────────────────────────────────────┤",
  "│                                                     │",
  '│  🔗 Website      <a href="' + website + '" target="_blank">falcon98.com</a>                      │',
  '│  💼 LinkedIn     <a href="' + linkedin + '" target="_blank">linkedin.com/in/ashen-wijesingha</a>  │',
  '│  🐙 GitHub       <a href="' + github + '" target="_blank">github.com/Falcon-98</a>                │',
  '│  📸 Instagram    <a href="' + instagram + '" target="_blank">@ashen_wijesingha</a>                 │',
  '│  📝 Medium       <a href="' + pmedium + '" target="_blank">@a.d.wijesingha</a>                    │',
  "│  📺 YouTube      Coming soon! 📹                   │",
  "│  🐦 Twitter      Coming soon! 🐦                   │",
  "│                                                     │",
  "╰─────────────────────────────────────────────────────╯",
  "",
];

// Contact Information
contact = [
  "",
  "╭─────────────────────────────────────────────────────────╮",
  "│                  📞 GET IN TOUCH                        │",
  "├─────────────────────────────────────────────────────────┤",
  "│                                                         │",
  "│  🏢 Business Inquiries (Falcon 98):                    │",
  '│     📧 Email:    <a href="' + email + '">terminal@falcon98.com</a>              │',
  "│     🌐 Website:  falcon98.com                          │",
  "│     📍 Based in: Colombo, Sri Lanka                    │",
  "│                                                         │",
  "│  👤 Personal & Professional Contact:                   │",
  '│     📧 Email:    <a href="' + pemail + '">a.d.wijesingha@gmail.com</a>         │',
  '│     📱 Phone:    <a href="' + pcontact + '">+94 78 446 4128</a>                    │',
  "│     📞 Landline: +94 11 340 1721                      │",
  '│     💼 LinkedIn: <a href="' + plinkedin + '" target="_blank">ashen-wijesingha</a>                     │',
  '│     🐙 GitHub:   <a href="' + pgithub + '" target="_blank">AshenWijesingha</a>                       │',
  '│     🌐 Portfolio: <a href="' + pwebsite + '" target="_blank">ashenwijesingha.github.io</a>            │',
  "│                                                         │",
  "│  ⏰ Availability:                                       │",
  "│     🕒 Response Time: Usually within 24 hours          │",
  "│     🌍 Timezone: GMT+5:30 (Sri Lanka)                  │",
  "│     🌟 Available 24/7 for professional opportunities   │",
  "│     💡 Open to freelance and consulting work           │",
  "│                                                         │",
  "│  🎯 Current Focus:                                      │",
  "│     • Cybersecurity consulting                         │",
  "│     • DevSecOps implementations                        │",
  "│     • AI-driven security solutions                     │",
  "│     • Cloud security architecture                      │",
  "│                                                         │",
  "╰─────────────────────────────────────────────────────────╯",
  "",
];

// Secret Information
secret = [
  "",
  "╭─────────────────────────────────────────────────────────╮",
  "│                🎉 ACCESS GRANTED! 🎉                   │",
  "├─────────────────────────────────────────────────────────┤",
  "│                                                         │",
  "│  🎊 Congratulations! You've unlocked Ashen's secret    │",
  "│      admin area! Welcome to the inner circle! 🔐       │",
  "│                                                         │",
  "│  🔐 Advanced Commands Available:                        │",
  "│     • matrix        - Enter the digital Matrix 🕶️     │",
  "│     • neofetch      - Detailed system information      │",
  "│     • ping          - Network diagnostics              │",
  "│     • leadership    - Leadership roles & achievements   │",
  "│                                                         │",
  "│  🏆 Achievement Unlocked: Cyber Terminal Master!       │",
  "│                                                         │",
  "│  💡 Easter Egg: Try 'matrix' for a cybersecurity      │",
  "│      professional's favorite digital experience! 😎     │",
  "│                                                         │",
  "│  🌟 'The best way to predict the future is to          │",
  "│      implement the security to protect it.' - Ashen    │",
  "│                                                         │",
  "╰─────────────────────────────────────────────────────────╯",
  "",
];

// Help Commands
help = [
  "",
  "╭─────────────────────────────────────────────────────────╮",
  "│                    📚 AVAILABLE COMMANDS                │",
  "├─────────────────────────────────────────────────────────┤",
  "│                                                         │",
  "│  Information Commands:                                  │",
  "│    help          Show this comprehensive help menu     │",
  "│    whois         About Falcon 98 company               │",
  "│    about         About Ashen Wijesingha                │",
  "│    skills        Technical skills & expertise          │",
  "│    experience    Professional work history             │",
  "│    education     Educational background & certifications│",
  "│    leadership    Leadership roles & achievements       │",
  "│    whoami        Philosophical digital question... 🤔   │",
  "│                                                         │",
  "│  Portfolio & Contact:                                   │",
  "│    projects      Featured projects & achievements      │",
  "│    social        Social media & professional links     │",
  "│    contact       Comprehensive contact information     │",
  "│                                                         │",
  "│  System Commands:                                       │",
  "│    clear         Clear terminal screen                 │",
  "│    history       Show command history                  │",
  "│    banner        Display welcome banner                │",
  "│    secret        🔐 Find the cybersec password...      │",
  "│                                                         │",
  "│  💡 Tips:                                               │",
  "│    • Use TAB for intelligent command completion         │",
  "│    • Use UP/DOWN arrows for command history            │",
  "│    • Try 'help --all' for advanced technical commands  │",
  "│    • Type 'leadership' to see achievements             │",
  "│                                                         │",
  "╰─────────────────────────────────────────────────────────╯",
  "",
];

// Advanced Help
advancedHelp = [
  "",
  "╭─────────────────────────────────────────────────────────╮",
  "│                  🔧 ADVANCED COMMANDS                   │",
  "├─────────────────────────────────────────────────────────┤",
  "│                                                         │",
  "│  System Information:                                    │",
  "│    neofetch      Display detailed system information   │",
  "│    date          Show current date and time            │",
  "│    uptime        Show terminal session uptime          │",
  "│    pwd           Show current directory path           │",
  "│    ls            List directory contents               │",
  "│    uname         Show system information               │",
  "│                                                         │",
  "│  Network & Diagnostics:                                │",
  "│    ping [host]   Network ping (try: ping falcon98.com) │",
  "│    whoami --system  Show browser/system details        │",
  "│                                                         │",
  "│  Utility Commands:                                      │",
  "│    echo [text]   Display text (supports variables)     │",
  "│    man [cmd]     Show manual pages for commands        │",
  "│                                                         │",
  "│  Cybersecurity Professional Commands:                  │",
  "│    matrix        Enter the Matrix (security themed) 😎 │",
  "│    leadership    View leadership roles & achievements   │",
  "│                                                         │",
  "│  Quick Professional Links:                             │",
  "│    github        Open GitHub profile                   │",
  "│    linkedin      Open LinkedIn (cybersec professional) │",
  "│    website       Open Falcon 98 main website          │",
  "│    email         Open email client                     │",
  "│    qr            Open QR Code Generator project        │",
  "│                                                         │",
  "│  🎯 Pro Tips for Recruiters:                           │",
  "│    • Use 'experience' for work history                 │",
  "│    • Use 'skills' for technical expertise              │",
  "│    • Use 'leadership' for achievements                 │",
  "│    • Use 'contact' for all contact methods             │",
  "│                                                         │",
  "╰─────────────────────────────────────────────────────────╯",
  "",
];